# Generated by Django 3.2.5 on 2021-08-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseHoldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_head', models.CharField(blank=True, max_length=100, null=True)),
                ('hh_gender', models.IntegerField(blank=True, null=True)),
                ('hh_age', models.IntegerField(blank=True, null=True)),
                ('hh_dob', models.DateTimeField(blank=True, null=True)),
                ('no_of_members', models.IntegerField(blank=True, null=True)),
                ('has_disability', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'House-Hold',
                'verbose_name_plural': 'House-Holds',
                'db_table': 'HOUSEHOLD',
                'managed': True,
            },
        ),
    ]
