# Generated by Django 3.2.5 on 2021-08-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbcolumn_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdmodel',
            name='hh_gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
